//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasparCGPlayout.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CasparCGPlayout.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_3 {
            get {
                object obj = ResourceManager.GetObject("arrow-left-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_3 {
            get {
                object obj = ResourceManager.GetObject("arrow-right-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Dog Disabled.
        /// </summary>
        internal static string Form1_btnDogToggle_Click_Channel_Dog_Disabled {
            get {
                return ResourceManager.GetString("Form1_btnDogToggle_Click_Channel_Dog_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Dog Enabled.
        /// </summary>
        internal static string Form1_btnDogToggle_Click_Channel_Dog_Enabled {
            get {
                return ResourceManager.GetString("Form1_btnDogToggle_Click_Channel_Dog_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMCP Connected.
        /// </summary>
        internal static string Form1_casparAmcpConnected_AMCP_Connected {
            get {
                return ResourceManager.GetString("Form1_casparAmcpConnected_AMCP_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMCP Disconnected.
        /// </summary>
        internal static string Form1_casparDevice_AMCPFailed_Connect_AMCP_Disconnected {
            get {
                return ResourceManager.GetString("Form1_casparDevice_AMCPFailed_Connect_AMCP_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to CasparCG Server: .
        /// </summary>
        internal static string Form1_casparDevice_AMCPFailed_Connect_Cannot_connect_to_CasparCG_Server__ {
            get {
                return ResourceManager.GetString("Form1_casparDevice_AMCPFailed_Connect_Cannot_connect_to_CasparCG_Server__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to run this Application with Elevated Rights to ensure system time accuracy.
        /// </summary>
        internal static string Form1_CheckUserPriveledges_It_is_recommended_to_run_this_Application_with_Elevated_Rights_to_ensure_system_time_accuracy {
            get {
                return ResourceManager.GetString("Form1_CheckUserPriveledges_It_is_recommended_to_run_this_Application_with_Elevate" +
                        "d_Rights_to_ensure_system_time_accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CasparCG Playout.
        /// </summary>
        internal static string Form1_connectDatabase_CasparCG_Playout {
            get {
                return ResourceManager.GetString("Form1_connectDatabase_CasparCG_Playout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATAL: Can&apos;t connect to MySQL Server. Exiting.
        /// </summary>
        internal static string Form1_connectDatabase_FATAL__Can_t_connect_to_MySQL_Server__Exiting {
            get {
                return ResourceManager.GetString("Form1_connectDatabase_FATAL__Can_t_connect_to_MySQL_Server__Exiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Connected.
        /// </summary>
        internal static string Form1_ConnectionStateChange_DB_Connected {
            get {
                return ResourceManager.GetString("Form1_ConnectionStateChange_DB_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Disconnected.
        /// </summary>
        internal static string Form1_ConnectionStateChange_DB_Disconnected {
            get {
                return ResourceManager.GetString("Form1_ConnectionStateChange_DB_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to wait to reconnect?.
        /// </summary>
        internal static string Form1_tmrConnectionCheck_Tick_ {
            get {
                return ResourceManager.GetString("Form1_tmrConnectionCheck_Tick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Database Server: .
        /// </summary>
        internal static string Form1_tmrConnectionCheck_Tick_Cannot_connect_to_Database_Server__ {
            get {
                return ResourceManager.GetString("Form1_tmrConnectionCheck_Tick_Cannot_connect_to_Database_Server__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Form1_tmrConnectionCheck_Tick_Connected {
            get {
                return ResourceManager.GetString("Form1_tmrConnectionCheck_Tick_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Query.
        /// </summary>
        internal static string Form1_tmrConnectionCheck_Tick_Important_Query {
            get {
                return ResourceManager.GetString("Form1_tmrConnectionCheck_Tick_Important_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Form1_tmrConnectionCheckTick_Disconnected {
            get {
                return ResourceManager.GetString("Form1_tmrConnectionCheckTick_Disconnected", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap media_seek_backward {
            get {
                object obj = ResourceManager.GetObject("media-seek-backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_seek_forward {
            get {
                object obj = ResourceManager.GetObject("media-seek-forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
